# Generated by Django 3.1.2 on 2021-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivitycheck',
            name='date',
            field=models.DateField(),
        ),
    ]
