# Generated by Django 3.1.2 on 2021-10-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20211004_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitusage',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
